### base config ###
# -*- coding: utf-8 -*-
full_field: &FULL_FIELD
  # BackBone Settings
  loss: 'l2'
  lr: 1E-3
  batch_size: 64
  num_data_workers: 0
  dt: 1                     # how many timesteps ahead the model will predict
  n_history: 0              # how many previous timesteps to consider
  prediction_type: 'iterative'
  prediction_length: 41     # applicable only if prediction_type == 'iterative'
  n_initial_conditions: 5   # applicable only if prediction_type == 'iterative'
  ics_type: "default"       # default or datetime
  date_strings: ["2018-09-14 00:00:00"]
  save_raw_forecasts: !!bool True
  save_channel: !!bool False
  masked_acc: !!bool False
  maskpath: None
  perturb: !!bool False
  add_grid: !!bool False
  N_grid_channels: 0
  gridtype: 'sinusoidal'    # options 'sinusoidal' or 'linear'
  roll: !!bool False
  enable_nhwc: !!bool False
  optimizer_type: 'FusedAdam'
  fusion_3d_2d: False
  backbone_params_path: './model.pth'

  # directory path to store training checkpoints and other output
  exp_dir: './exp_finetune'

  # data
  train_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train'
  valid_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/valid'  
  test_data_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/test'

  # land mask
  land_mask: !!bool True
  land_mask_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/land_mask.h5'

  # normalization
  normalize: !!bool True
  normalization: 'zscore' # options zscore or minmax
  global_mins_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_mins.npy' 
  global_maxs_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_maxs.npy' 
  global_means_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_means.npy' 
  global_stds_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_stds.npy' 

  # orography
  orography: !!bool True
  orography_norm_zscore_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/orography_norm_zscore.h5'
  orography_norm_maxmin_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/orography_norm_maxmin.h5'
  
  # Demension
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ,21, 22, 23, 24, 25, 26, 27, 28, 29]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
  N_in_channels: 31
  N_out_channels: 25

  # noise
  add_noise: !!bool False
  noise_std: 0

  # crop
  crop_size_x: None
  crop_size_y: None

  log_to_screen: !!bool True
  log_to_wandb: !!bool True
  save_checkpoint: !!bool True
  plot_animations: !!bool False
  
#############################################
WaveNet: &WaveNet
  <<: *FULL_FIELD
  nettype: 'WaveNet'
  log_to_wandb: !!bool True

  # Train params
  lr: 1E-3
  batch_size: 16
  max_epochs: 100
  scheduler: 'CosineAnnealingLR'
  
  # Finetune Model Settings
  target_in_chans: 0
  target_chans: 1
  target_size_h: 360
  target_size_w: 720


  # Wave Data
  train_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train'
  valid_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/valid'  
  test_data_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/test'

  # Wave Data normalization
  normalize: !!bool True
  normalization: 'zscore' # options zscore or minmax
  global_mins_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_mins.npy' 
  global_maxs_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_maxs.npy' 
  global_means_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_means.npy' 
  global_stds_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_stds.npy'

#############################################


#############################################
BiochemicalNet: &BiochemicalNet
  <<: *FULL_FIELD
  nettype: 'BiochemicalNet'
  log_to_wandb: !!bool True

  # Train params
  lr: 1E-3
  batch_size: 16
  max_epochs: 100
  scheduler: 'CosineAnnealingLR'
  
  # Finetune Model Settings
  target_in_chans: 8
  target_chans: 8
  target_size_h: 180
  target_size_w: 360

  # Biochemical Data
  train_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train'
  valid_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/valid'  
  test_data_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/test'

  # Biochemical Data normalization
  normalize: !!bool True
  normalization: 'zscore' # options zscore or minmax
  global_mins_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_mins.npy' 
  global_maxs_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_maxs.npy' 
  global_means_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_means.npy' 
  global_stds_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_stds.npy'
#############################################


############################################# 
DownScalingNet: &DownScalingNet
  <<: *FULL_FIELD
  nettype: 'DownScalingNet'
  log_to_wandb: !!bool True

  # Train params
  lr: 1E-3
  batch_size: 16
  max_epochs: 100
  scheduler: 'CosineAnnealingLR'
  
  # Finetune Model Settings
  target_in_chans: 0
  target_chans: 5
  target_size_h: 313
  target_size_w: 687

  downstream_train_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train'
  downstream_valid_data_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/valid'  
  downstream_test_data_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/test'

  normalize: !!bool True
  normalization: 'zscore' # options zscore or minmax
  downstream_mins_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_mins.npy' 
  downstream_maxs_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_maxs.npy' 
  downstream_means_path: '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_means.npy' 
  downstream_stds_path:  '/home/bingxing2/home/scx6115/Ocean_AI_model/sample_00/train/global_stds.npy'
  
 
